# Generated by Django 2.1.3 on 2018-12-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('death_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gallery Artist',
                'verbose_name_plural': 'Gallery Artists',
                'db_table': 'artist',
                'ordering': ['artist_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistRole',
            fields=[
                ('artist_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_role_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Artist Role in Artworks',
                'verbose_name_plural': 'Artist Roles in Artworks',
                'db_table': 'artist_role',
                'ordering': ['artist_role_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('artwork_id', models.AutoField(primary_key=True, serialize=False)),
                ('artwork_name', models.CharField(max_length=999)),
                ('accession_number', models.CharField(max_length=6)),
                ('date_text', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('credit_line', models.CharField(max_length=999)),
                ('acquisition_year', models.IntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('depth', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gallery Artwork',
                'verbose_name_plural': 'Gallery Artworks',
                'db_table': 'artwork',
                'ordering': ['accession_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtworkSubject',
            fields=[
                ('artwork_subject_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Gallery Artwork Subject',
                'verbose_name_plural': 'Gallery Artwork Subjects',
                'db_table': 'artwork_subject',
                'ordering': ['artwork', 'subject'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Artist Gender',
                'verbose_name_plural': 'Artist Genders',
                'db_table': 'gender',
                'ordering': ['gender_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Birth and Death place of Artists',
                'verbose_name_plural': 'Birth and Death places of Artists',
                'db_table': 'place',
                'ordering': ['place_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.IntegerField()),
                ('subject_name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Subject Shown in Artworks',
                'verbose_name_plural': 'Subject Shown in Artworks',
                'db_table': 'subject',
                'ordering': ['subject_name'],
                'managed': False,
            },
        ),
    ]
